name: My First Github Actions
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Build the Project
        run: npm run build
      - name: Setup Finish
        run: echo "Hurrayy!!"